### ISSUE TITLE
Home Slider Height 

### ISSUE THREAD

**Issue by LiyoloMoko** [cqudefus/zibonel#1]
The height of the slider has to be smaller a bit, it shouldn't be full screen as it is

**Comment by berkaayowa** [comment]
Will do it on 12/09

**Comment by LiyoloMoko** [comment]
Have you gotten a chance to do it ?

**Comment by sithembisoa** [comment]
@LiyoloMoko go to theme-bottle.css line 1050 change the value of .h-lg { height: 86vh; } to your desired height
