### ISSUE TITLE
Slider Design

### ISSUE THREAD

**Issue by LiyoloMoko** [cqudefus/zibonel#2]
Try to have the slider have 3 in one 
![whatsapp image 2017-09-11 at 8 59 51 am](https://user-images.githubusercontent.com/19814290/30284407-17308cb0-96d8-11e7-8e57-c301bfc2011b.jpeg)

**Comment by LiyoloMoko** [comment]
the want something like that https://www.iol.co.za/vukani/news

**Comment by berkaayowa** [comment]
I won't fixed this, it was not on the scope

**Comment by berkaayowa** [comment]
they need, to pay for
