### ISSUE TITLE
News - Deleted the old ones and added the new posts thru backend as user

### ISSUE THREAD

**Issue by LiyoloMoko** [cqudefus/zibonel#6]
Please fix those bugs 
![capture1](https://user-images.githubusercontent.com/19814290/30580671-a001ccfe-9cda-11e7-9670-b801ee39c0a2.PNG)
![capture2](https://user-images.githubusercontent.com/19814290/30580672-a00c389c-9cda-11e7-99f3-e74e06a5f4ee.PNG)

**Comment by berkaayowa** [comment]
Fixed that bug
